
on: 
  push:
    branches: [main]
  pull_request:
    types:  [closed]
    branches: [main]



  
name: Linux Container Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v1
          with:
            login-server: roehampton.azurecr.io
            username: roehampton
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t roehampton.azurecr.io/hsbs:${{ github.sha }}
            docker push roehampton.azurecr.io/hsbs:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: project
            dns-name-label: planetdoctor
            ports: 3000
            name: planetdoctor
            image: roehampton.azurecr.io/hsbs:${{ github.sha }}
            location: uksouth
            registry-username: roehampton
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            registry-login-server: roehampton.azurecr.io
